strategies:
  azure:
    secret: ${AZURE_SECRET}
    client_id: ${AZURE_CLIENT_ID}
    redirect_uri: ${AZURE_REDIRECT_URI}
    tenant: ${AZURE_TENANT}

  jwt:
    secret: ${JWT_SECRET}
    issuer: ${JWT_ISSUER}
    expiresIn: ${JWT_EXPIRESIN}
    ignoreExpiration: ${JWT_IGNOREEXPIRE}

allow_signup: ${ALLOW_SIGNUP}
web_redirect_url: ${WEB_REDIRECT_URL}